#!/user/bin/python

import PyPDF2
pdfFile = open('grd20171EN.pdf', 'rb')
pdfReader = PyPDF2.PdfFileReader(pdfFile)
pdfReader.numPages

#TODO: read from all pages by iterating through numPages
page1 = pdfReader.getPage(0).extractText().split('\n')