# Generated by Django 2.0.4 on 2018-04-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('short', models.CharField(max_length=12)),
                ('term_code', models.CharField(max_length=6)),
                ('name', models.CharField(default='', max_length=125)),
                ('credits', models.IntegerField(null=True)),
                ('description', models.TextField(max_length=300, null=True)),
                ('division_of_hours', models.TextField(max_length=100, null=True)),
                ('prereqs', models.TextField(max_length=150, null=True)),
            ],
            options={
                'ordering': ('_id',),
            },
        ),
    ]
