# Generated by Django 2.0.4 on 2018-04-14 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(max_length=30)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('days', models.CharField(max_length=7, null=True)),
            ],
            options={
                'ordering': ('start_time',),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('_id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('term_code', models.IntegerField()),
                ('crn', models.IntegerField()),
                ('section_num', models.CharField(max_length=4)),
                ('honors', models.BooleanField(default=False)),
                ('section_name', models.CharField(max_length=60)),
                ('credits', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('meetings', models.ManyToManyField(to='sections.Meeting')),
            ],
            options={
                'ordering': ('honors', 'section_num'),
            },
        ),
    ]
