# Generated by Django 2.0.4 on 2018-04-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={
                'ordering': (
                    'honors',
                    'section_num')},
        ),
        migrations.RenameField(
            model_name='section',
            old_name='name',
            new_name='section_name',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='section',
            new_name='section_num',
        ),
        migrations.AddField(
            model_name='section',
            name='credits',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=4,
                null=True),
        ),
    ]
