# Generated by Django 2.0.4 on 2018-04-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_auto_20180413_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='days',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
