# Generated by Django 2.0.4 on 2018-05-18 05:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('abbr', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=11)),
            ],
            options={
                'ordering': ('abbr',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('dept', models.CharField(db_index=True, max_length=5)),
                ('course_num', models.CharField(max_length=5)),
                ('short', models.CharField(max_length=12)),
                ('term_code', models.CharField(db_index=True, max_length=6)),
                ('name', models.CharField(db_index=True, default='', max_length=125)),
                ('least_credits', models.FloatField(null=True)),
                ('most_credits', models.FloatField(null=True)),
                ('description', models.TextField(max_length=300, null=True)),
                ('division_of_hours', models.TextField(max_length=100, null=True)),
                ('prereqs', models.TextField(max_length=150, null=True)),
            ],
            options={
                'ordering': ('_id',),
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('_id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(max_length=30)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('days', models.CharField(max_length=7, null=True)),
            ],
            options={
                'ordering': ('start_time',),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('_id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('term_code', models.IntegerField()),
                ('crn', models.IntegerField()),
                ('dept', models.CharField(max_length=5)),
                ('course_num', models.CharField(max_length=5)),
                ('section_num', models.CharField(max_length=4)),
                ('honors', models.BooleanField(default=False)),
                ('section_name', models.CharField(max_length=60)),
                ('least_credits', models.FloatField(null=True)),
                ('most_credits', models.FloatField(null=True)),
            ],
            options={
                'ordering': ('honors', 'section_num'),
            },
        ),
        migrations.CreateModel(
            name='GPADistribution',
            fields=[
                ('ABCDFQ', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('gpa', models.FloatField(verbose_name='The overall course GPA.')),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='gpa_distribution', serialize=False, to='goodbullapi.Section')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections_taught', to='goodbullapi.Instructor')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='goodbullapi.Course'),
        ),
        migrations.AddField(
            model_name='section',
            name='meetings',
            field=models.ManyToManyField(to='goodbullapi.Meeting'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('dept', 'course_num', 'term_code')},
        ),
    ]
