# Generated by Django 2.0.4 on 2018-04-14 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('abbr', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=11)),
            ],
            options={
                'ordering': ('abbr',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('short', models.CharField(max_length=12)),
                ('term_code', models.CharField(max_length=6)),
                ('name', models.CharField(default='', max_length=125)),
                ('credits', models.IntegerField(null=True)),
                ('description', models.TextField(max_length=300, null=True)),
                ('division_of_hours', models.TextField(max_length=100, null=True)),
                ('prereqs', models.TextField(max_length=150, null=True)),
            ],
            options={
                'ordering': ('_id',),
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(max_length=30)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('days', models.CharField(max_length=7, null=True)),
            ],
            options={
                'ordering': ('start_time',),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('_id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('term_code', models.IntegerField()),
                ('crn', models.IntegerField()),
                ('section_num', models.CharField(max_length=4)),
                ('honors', models.BooleanField(default=False)),
                ('section_name', models.CharField(max_length=60)),
                ('credits', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='goodbullapi.Course')),
                ('meetings', models.ManyToManyField(to='goodbullapi.Meeting')),
            ],
            options={
                'ordering': ('honors', 'section_num'),
            },
        ),
    ]
