# Generated by Django 2.0.4 on 2018-05-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodbullapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='least_credits',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='most_credits',
            field=models.FloatField(null=True),
        ),
    ]
