# Generated by Django 2.0.4 on 2018-05-17 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodbullapi', '0002_auto_20180517_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpadistribution',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections_taught', to='goodbullapi.Instructor'),
        ),
    ]
